version: '3.8'

services:
  influxdb:
    image: influxdb:2.0
    container_name: weg-segura-influxdb
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=wegsegura123
      - DOCKER_INFLUXDB_INIT_ORG=WegSegura
      - DOCKER_INFLUXDB_INIT_BUCKET=WegSegura
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=nU8725HIFJQYxLu0dbOKyVuNjQfrBaZf0bSi6pakaVNkG3BbygOEzSjtTRJ9sZ1JtdHfCZ9YXRPlWCbIQgHr0g==
    volumes:
      - influxdb_data:/var/lib/influxdb2
      - influxdb_config:/etc/influxdb2
    restart: unless-stopped

volumes:
  influxdb_data:
  influxdb_config:
